// <auto-generated />
using System;
using Helix.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Helix.API.Migrations
{
    [DbContext(typeof(HelixDbContext))]
    [Migration("20260314144608_AddMetrics")]
    partial class AddMetrics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Helix.API.Data.GenomicJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlignedSequenceA")
                        .HasColumnType("text");

                    b.Property<string>("AlignedSequenceB")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FinalScore")
                        .HasColumnType("integer");

                    b.Property<int?>("Gaps")
                        .HasColumnType("integer");

                    b.Property<double?>("IdentityPercentage")
                        .HasColumnType("double precision");

                    b.Property<int?>("Matches")
                        .HasColumnType("integer");

                    b.Property<int?>("Mismatches")
                        .HasColumnType("integer");

                    b.Property<string>("SequenceA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SequenceB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GenomicJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
